<pre>
--- <a href=https://adventofcode.com/2021/day/7> Day 7: The Treachery of Whales  </a> ---

Determine the horizontal position that the crabs can align to using the least fuel possible. 
<b>How much fuel must they spend to align to that position? </b>
</pre>

In [3]:
import numpy as np

In [99]:
%%time
positions = np.loadtxt("input_test", delimiter=",", dtype=int)
position = np.arange(positions.min(), positions.max(), dtype=int)
np.abs(np.subtract(position.reshape(-1, 1),  np.tile(positions, position.shape).reshape(position.shape[0], -1))).sum(axis=1).min()

CPU times: user 1.16 ms, sys: 201 µs, total: 1.36 ms
Wall time: 902 µs


37

In [98]:
%%time
positions = np.loadtxt("input", delimiter=",", dtype=int)
position = np.arange(positions.min(), positions.max(), dtype=int)
np.abs(np.subtract(position.reshape(-1, 1),  np.tile(positions, position.shape).reshape(position.shape[0], -1))).sum(axis=1).min()

CPU times: user 5.04 ms, sys: 7.5 ms, total: 12.5 ms
Wall time: 11.8 ms


353800

<pre>
--- Part Two --- 

Determine the horizontal position that the crabs can align to using the least fuel possible so they can make you an escape route! 
<b>How much fuel must they spend to align to that position?</b>

</pre>

In [128]:
positions = np.loadtxt("input_test", delimiter=",", dtype=int)
print(positions)

n = np.arange(positions.min(), positions.max(), dtype=int)
n = np.tile(n, positions.shape[0]).reshape(positions.shape[0], -1)
moves = np.abs(np.subtract(n, positions.reshape(-1, 1)))

f = lambda x: np.arange(x+1).sum()
fv = np.vectorize(f)
print(moves)

fv(moves).sum(axis=0).min()

[16  1  2  0  4  2  7  1  2 14]
[[16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
 [ 1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [ 2  1  0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 4  3  2  1  0  1  2  3  4  5  6  7  8  9 10 11]
 [ 2  1  0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [ 7  6  5  4  3  2  1  0  1  2  3  4  5  6  7  8]
 [ 1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [ 2  1  0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [14 13 12 11 10  9  8  7  6  5  4  3  2  1  0  1]]


168