```
--- Day 1: Sonar Sweep ---

How many measurements are larger than the previous measurement?
``` 

In [3]:
import numpy as np

In [18]:
input_ = [199, 200, 208, 210, 200, 207, 240, 269, 260, 263]

In [19]:
input_ = np.array(input_)
display(np.diff(input_))
(np.diff(input_) > 0).sum()

array([  0,   1,   8,   2, -10,   7,  33,  29,  -9,   3])

7

In [27]:
input_ = np.fromfile("input", dtype=int, sep='\n')
input_

array([ 196,  197,  176, ..., 3724, 3723, 3728])

In [28]:
(np.diff(input_) > 0).sum()

1228

```
Consider sums of a three-measurement sliding window. How many sums are larger than the previous sum?
```

In [29]:
input_ = [199, 200, 208, 210, 200, 207, 240, 269, 260, 263]

In [48]:
display(np.convolve(input_, np.ones(3), mode="valid"))

array([607., 618., 618., 617., 647., 716., 769., 792.])

In [52]:
sum(np.diff(np.convolve(input_, np.ones(3), mode="valid")) > 0 )

5

In [53]:
input_ = np.fromfile("input", dtype=int, sep='\n')
sum(np.diff(np.convolve(input_, np.ones(3), mode="valid")) > 0 )

1257