In [1]:
import numpy as np

```np.reshape(a, shape, order='C') ```
```python
order=C  C-like: Last index changing fastest
order=F  Fortran-like: First index changing fastest

```


In [2]:
size = [25, 6]
with open("input.txt") as f:
    image = np.array(list(f.read().strip()), dtype=int)

size.append(-1)
image = image.reshape(size, order="F")

print(image.shape)

(25, 6, 100)


In [3]:
image2 = image.reshape([size[0] * size[1], size[2]])
print(image2.shape)
ilayer = np.count_nonzero(image2, axis=0).argmax()
print(ilayer)

layer = image[:,:, ilayer]
unique, counts = np.unique(layer.flatten(), return_counts=True)
info = dict(zip(unique, counts))
print(info)
info[1] * info[2]

(150, 100)
5
{0: 4, 1: 15, 2: 131}


1965

In [4]:
size = [-1, 6, 25]
with open("input.txt") as f:
    image = np.array(list(f.read().strip()), dtype=int)

image = image.reshape(size)

print(image.shape)

(100, 6, 25)


In [5]:
image2 = image.reshape([size[0],  size[1] * size[2]])
print(image2.shape)
ilayer = np.count_nonzero(image2, axis=1).argmax()
print(ilayer)

layer = image[ilayer, :,:]
print(layer.shape)
unique, counts = np.unique(layer.flatten(), return_counts=True)
info = dict(zip(unique, counts))
print(info)
info[1] * info[2]

(100, 150)
5
(6, 25)
{0: 4, 1: 15, 2: 131}


1965

```--- Part Two ---```

In [117]:
size=[-1, 6,  25]
with open("input.txt") as f:
    image = np.array(list(f.read().strip()), dtype=int)

image = image.reshape(size)

print(image.shape)

(100, 6, 25)


In [119]:
def foo(array):
    return array[np.nonzero(array!=2)[0][0]]
    
pixels = np.apply_along_axis(foo, 0, image)
print(pixels)

[[0 1 1 0 0 1 1 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1]
 [1 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 1]
 [1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 1 0]
 [1 0 1 1 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 0 0]
 [1 0 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 1 0 0]
 [0 1 1 1 0 1 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0 0]]


In [121]:
%matplotlib notebook

from PIL import Image
from matplotlib import cm
pixels[np.where(pixels==1)] = 255
print(pixels.shape)
#im = Image.fromarray(np.uint8(cm.gist_earth(pixels)*255))
Image.fromarray(np.uint8(pixels))

(6, 25)
