In [5]:
import numpy as np

### Part I
What is the ID of the earliest bus you can take to the airport multiplied by the number of minutes you'll need to wait for that bus?

In [6]:
with open("input_sample") as f:
    time = int(f.readline())
    buses = np.array([int(x) for x in f.readline().split(",") if x != 'x'])

print(time)
print(buses)

939
[ 7 13 59 31 19]


In [26]:
minutes = (np.ceil(time / buses) * buses) - time
argmin = np.argmin(minutes)
buses[argmin] * minutes[argmin]

295.0

In [27]:
with open("input") as f:
    time = int(f.readline())
    buses = np.array([int(x) for x in f.readline().split(",") if x != 'x'])

print(time)
print(buses)

1002576
[ 13  37 449  29  19  23 773  41  17]


In [28]:
minutes = (np.ceil(time / buses) * buses) - time
argmin = np.argmin(minutes)
buses[argmin] * minutes[argmin]

3865.0

### Part II
What is the earliest timestamp such that all of the listed bus IDs depart at offsets matching their positions in the list?

In [35]:
with open("input_sample") as f:
    f.readline()
    buses = np.array([int(x) if x!= 'x' else np.nan for x in f.readline().split(",") ])

print(buses)

[ 7. 13. nan nan 59. nan 31. 19.]


In [133]:
from numpy import linalg

# Build the equation system



ok = ~np.isnan(buses)
indexes = np.arange(0, buses.shape[0])[ok]
print(indexes)


n = (~np.isnan(buses)).sum()
A = np.zeros((n-1, n))
b = np.zeros((n-1))

row = 0
for i in range(1, n):
    #print(i)
    A[row][i]  = buses[ok][i]
    A[row][0]  = -buses[ok][0]
    b[row] = indexes[i] 
    #print(i - iant)
    #print(i, buses[i], buses[iant])
    
    row += 1

print(A, b)

np.linalg.lstsq(A, b)

[0 1 4 6 7]
[[-7. 13.  0.  0.  0.]
 [-7.  0. 59.  0.  0.]
 [-7.  0.  0. 31.  0.]
 [-7.  0.  0.  0. 19.]] [1. 4. 6. 7.]


/home/xavi/anaconda3/envs/devel/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


(array([-0.15354948, -0.00575741,  0.04957888,  0.15887592,  0.31185019]),
 array([], dtype=float64),
 4,
 array([59.43507934, 31.87830204, 20.37274927, 14.28972673]))

In [182]:
%%time
for a  in range(0, 1000000):
    t = buses[0] * a
    
    solution = np.linalg.solve(A[:, 1:], b - a * A[:,0])
    if (np.abs(solution - np.round(solution)) < 0.001).all():
        print(t, solution)
        break
    
    
    
    

1068781.0 [82214. 18115. 34477. 56252.]
CPU times: user 2.39 s, sys: 0 ns, total: 2.39 s
Wall time: 2.39 s


In [183]:
with open("input") as f:
    f.readline()
    buses = np.array([int(x) if x!= 'x' else np.nan for x in f.readline().split(",") ])

print(buses)

[ 13.  nan  nan  nan  nan  nan  nan  37.  nan  nan  nan  nan  nan 449.
  nan  29.  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
  nan  nan  nan  nan  19.  nan  nan  nan  23.  nan  nan  nan  nan  nan
  nan  nan 773.  nan  nan  nan  nan  nan  nan  nan  nan  nan  41.  nan
  nan  nan  nan  nan  nan  17.]


In [185]:
from numpy import linalg

# Build the equation system



ok = ~np.isnan(buses)
indexes = np.arange(0, buses.shape[0])[ok]
print(indexes)


n = (~np.isnan(buses)).sum()
A = np.zeros((n-1, n))
b = np.zeros((n-1))

row = 0
for i in range(1, n):
    #print(i)
    A[row][i]  = buses[ok][i]
    A[row][0]  = -buses[ok][0]
    b[row] = indexes[i] 
    #print(i - iant)
    #print(i, buses[i], buses[iant])
    
    row += 1

print(A, b)


[ 0  7 13 15 32 36 44 54 61]
[[-13.  37.   0.   0.   0.   0.   0.   0.   0.]
 [-13.   0. 449.   0.   0.   0.   0.   0.   0.]
 [-13.   0.   0.  29.   0.   0.   0.   0.   0.]
 [-13.   0.   0.   0.  19.   0.   0.   0.   0.]
 [-13.   0.   0.   0.   0.  23.   0.   0.   0.]
 [-13.   0.   0.   0.   0.   0. 773.   0.   0.]
 [-13.   0.   0.   0.   0.   0.   0.  41.   0.]
 [-13.   0.   0.   0.   0.   0.   0.   0.  17.]] [ 7. 13. 15. 32. 36. 44. 54. 61.]


In [187]:
%%time
while True:
    t = buses[0] * a
    solution = np.linalg.solve(A[:, 1:], b - a * A[:,0])
    if (np.abs(solution - np.round(solution)) < 0.001).all():
        print(t, solution)
        break

KeyboardInterrupt: 